# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hidwWD-kPHDDbJBCDwEu7tJ8SM-rf0o5
"""

import streamlit as st
import pandas as pd

# Load dataset
df = pd.read_csv("smart_travel_maharashtra_full.csv")

st.set_page_config(page_title="Smart Travel Planner", page_icon="🧳", layout="wide")
st.title("🧠 Smart Travel Planner - Maharashtra Edition")
st.markdown("Plan your next trip with intelligent insights and real user reviews!")

# Sidebar for filtering
st.sidebar.header("🔎 Filter Your Preferences")
category = st.sidebar.selectbox("Choose Category", sorted(df['Category'].unique()))
city = st.sidebar.selectbox("Choose City", sorted(df['Location'].unique()))

# Filter data
filtered = df[(df['Category'] == category) & (df['Location'] == city)]

# Group by unique places
grouped = filtered.groupby(['Place_Name', 'Opening_Hours', 'Temperature', 'Weather']).agg({
    'Rating': 'mean',
    'Sentiment': lambda x: (x == 'positive').sum()
}).reset_index()

# Display recommendations
st.subheader(f"📍 Top {category} Places in {city}")
if grouped.empty:
    st.warning("No results found for your selection.")
else:
    for _, row in grouped.iterrows():
        with st.expander(f"{row['Place_Name']}"):
            st.markdown(f"""
            **🕒 Opening Hours**: {row['Opening_Hours']}
            **🌡 Temperature**: {row['Temperature']}
            **🌦 Weather**: {row['Weather']}
            **⭐ Average Rating**: {round(row['Rating'], 2)}
            **👍 Positive Reviews**: {row['Sentiment']}
            """)

# Closing message
st.success("✨ Thank you for using the Smart Travel Planner! ✨")